Small edit

diff --git a/weather-yr-pdf b/weather-yr-pdf
--- a/weather-yr-pdf
+++ b/weather-yr-pdf
@@ -5,14 +5,66 @@ YR_PDF=($WEATHERPATH/*)
 DATE="$(date +%Y-%m-%d)"
 GEO_LOCATION=$(cat "$HOME/Documents/yr-location")
 
-if [[ "$1" == "v" ]]; then
+
+olderData () {
     SELECTION=$(printf '%s\n' "${YR_PDF[@]}" | awk -F "/" '{print $NF}' | dmenu -i -c -l 20 -p "Weather files: ")
     [[ ! "$SELECTION" ]] && exit 1
     devour zathura "$WEATHERPATH/$SELECTION"
-elif [[ ! -f "$WEATHERPATH/$DATE-forecast.pdf" ]]; then
-    cd $HOME/Documents/vær
-    wget -O "$DATE-forecast.pdf" "$GEO_LOCATION"
-    devour zathura "$WEATHERPATH/$DATE-forecast.pdf"
-else
-    devour zathura "$WEATHERPATH/$DATE-forecast.pdf"
-fi
+}
+
+weatherNow () {
+    if [[ ! -f "$WEATHERPATH/$DATE-forecast.pdf" ]]; then
+        cd $HOME/Documents/vær
+        wget -O "$DATE-forecast.pdf" "$GEO_LOCATION"
+        devour zathura "$WEATHERPATH/$DATE-forecast.pdf"
+    else
+        devour zathura "$WEATHERPATH/$DATE-forecast.pdf"
+    fi
+}
+
+viewOtherPlaces () {
+    declare -a places=(
+        "Tromsø"
+        "Bjerkvik"
+        "Bardufoss"
+        "Skitdalshøgda"
+        "Veggfjellet"
+        "E6-Gratangsfjellet"
+    )
+    LOCATION=$(printf '%s\n' "${places[@]}" | dmenu -i -l 20 -p "Places: ")
+    [[ ! "$LOCATION" ]] && exit 1
+    if [[ ! -f "/tmp/$LOCATION" ]]; then
+        case $LOCATION in
+            Tromsø )
+                cd "/tmp"
+                wget -O "$DATE-$LOCATION.pdf" "https://www.yr.no/nb/utskrift/v%C3%A6rvarsel/1-305409/Norge/Troms%20og%20Finnmark/Troms%C3%B8/Troms%C3%B8";;
+            Bjerkvik )
+                cd "/tmp"
+                wget "https://www.yr.no/nb/utskrift/v%C3%A6rvarsel/1-541925/Norge/Nordland/Narvik/Bjerkvik";;
+            Bardufoss )
+                cd "/tmp"
+                wget "https://www.yr.no/nb/utskrift/v%C3%A6rvarsel/1-296475/Norge/Troms%20og%20Finnmark/M%C3%A5lselv/Bardufoss";;
+            Skitdalshødga )
+                cd "/tmp"
+                wget "https://www.yr.no/nb/utskrift/v%C3%A6rvarsel/1-2214107/Norge/Nordland/Narvik/Skitdalsh%C3%B8gda";;
+            Maridalen )
+                cd "/tmp"
+                wget "https://www.yr.no/nb/utskrift/v%C3%A6rvarsel/1-283059/Norge/Nordland/Evenes/Veggfjellet";;
+            Gratangsfjellet )
+                cd "/tmp"
+                wget "https://www.yr.no/nb/utskrift/v%C4%A6rvarsel/5-88010/Norge/Troms%20og%20Finnmark/Lavangen/E6%20Gratangsfjellet";;
+        esac
+    fi
+    devour zathura "/tmp/$LOCATION"
+}
+
+while getopts "nod" opt
+do
+    case ${opt} in
+        n ) weatherNow;; # n for now
+        o ) olderData;; # o for older
+        d ) viewOtherPlaces;; # d for different place
+        /? ) echo "Invalid Option: "; exit 1;;
+    esac
+done
+
